### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by camjac251** [KaitoCross/TacoTranscribe#1]
Are you still supporting this project? I came across it through searching for tacotron ljspeech related stuff and it's one of the few out there.

I attempted to build it through QT Creator on Windows 10 but am only able to run it from QT Creator, building isn't working.

When running though, I'm confused on how to load LJSpeech data. I attempted to select the wavs folder as the audio source and when choosing "Load script" and selecting the csv (even though it's showing in the load script and save script, .txt instead of .csv)

Is this made for Windows? When I loaded the csv on load script and try to play it, it'll say "Audiofile not found! C:\Users\User\Downloads\LJSpeech-1.1\wavs/Printing, in the only sense with which we are at present concerned, diffe" before getting cut off by the window size. Even though it shows the file on the top as LJ001-0001.

**Comment by KaitoCross** [comment]
I'm still supporting this. It's made for all OSes.
Unfortunately, the editor parses the data wrong. 
While LJSpeech scripts are structured like
`Audiofilename (without file extension)|Transcription|Normalized Transcription`
the editor expects the file to be structured like
`Transcription|Normalized Transcription|Audiofile.wav`
Therefore, this editor is not LJSpeech-compliant. The fix is simple though.

The way you loaded the data was correct, it's just that the program interprets the file structure differently.
Save Savepoint -> Save current progress
Save Script -> Saving the script (new file) you are working on in case you had to mark lines as unusable/missing.
To resume working, you'd have to first load the audio, then load the new script file created in the last session, and then load the savepoint file. 

Unfortunately I can't help you with building, as I'm mainly using Linux. I have tried it on Windows a long while ago and it somehow worked when it was bundled with the right DLLs provided through some QT tool.

**Comment by camjac251** [comment]
Thank you for replying so quickly. I'll try formatting it like that before importing. It was a bit confusing because the description says "LJSpeech-like" for this repo so I assumed that it was compatible.

Would it be possible to have something like AppVeyor handle automated builds? They're mainly for Windows builds but QT on their platform.

**Comment by KaitoCross** [comment]
I fixed the problems with the LJSpeech format.
The current version allows to load them as LJSpeech-like files. It however has to use a modified version.
While LJSpeech scripts are structured like
`Audiofilename (without file extension)|Transcription|Normalized Transcription`
my editor expects the LJSpeech scripts to be structured like
`Audiofilename.wav (or any other extension)|Transcription|Normalized Transcription`

The old way of reading the files still works. When saving or loading files, you have to choose the script structure correctly using the file type dropdown menu. The standard is now the LJSpeech-like format. If you wanna keep using the old not-compliant format, choose the non-compliant in the file type menu.
